title: "Somerset Geology"
description: Somerset Geology Group - Local Geological Sites in Somerset
remote_theme: just-the-docs/just-the-docs
url: https://geoffrowland.github.io/somersetgeology
search_enabled: true
# Aux links for the upper right navigation
#aux_links:
#  "Somerset Environmental Records Centre":
#    - "//www.somerc.com/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
# External navigation links
nav_external_links:
  - title: SERC
    url: https://www.somerc.com/
    hide_icon: false # set to true to hide the external link icon - defaults to false
